CREATE DATABASE IF NOT EXISTS academia
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE academia;

CREATE TABLE IF NOT EXISTS alumnos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  correo VARCHAR(255) NOT NULL UNIQUE,
  idioma VARCHAR(50) NOT NULL,
  fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);